# Numpy Tutorial

In [2]:
import numpy as np

### Writing

In [3]:
data = np.random.rand(2,3,4)
zeroes = np.zeros((2,2,2))
full = np.full((2,2,2), 7)
ones = np.ones(((2,2,2)))

data, zeroes, full, ones

(array([[[0.79526664, 0.01278876, 0.04911231, 0.88678336],
         [0.45008317, 0.39721963, 0.38715577, 0.88333943],
         [0.24865133, 0.67217365, 0.81114603, 0.1140222 ]],
 
        [[0.42523713, 0.48740159, 0.6799291 , 0.46620409],
         [0.24792823, 0.90302225, 0.36170425, 0.14065124],
         [0.40962195, 0.81329592, 0.94150884, 0.629578  ]]]),
 array([[[0., 0.],
         [0., 0.]],
 
        [[0., 0.],
         [0., 0.]]]),
 array([[[7, 7],
         [7, 7]],
 
        [[7, 7],
         [7, 7]]]),
 array([[[1., 1.],
         [1., 1.]],
 
        [[1., 1.],
         [1., 1.]]]))

In [4]:
arr = np.array([[1,2,3,4],[1,2,3,4]])
type(arr)

numpy.ndarray

### Reading

In [5]:
shape = data.shape
size = data.size
types = data.dtype

In [6]:
types

dtype('float64')

In [7]:
#slicing
arr = data[0]
slicer = data[0][0:2]
reverse = data[-1]
singlevel = data[0][0][0]

In [8]:
arr

array([[0.79526664, 0.01278876, 0.04911231, 0.88678336],
       [0.45008317, 0.39721963, 0.38715577, 0.88333943],
       [0.24865133, 0.67217365, 0.81114603, 0.1140222 ]])

In [9]:
slicer

array([[0.79526664, 0.01278876, 0.04911231, 0.88678336],
       [0.45008317, 0.39721963, 0.38715577, 0.88333943]])

In [10]:
reverse

array([[0.42523713, 0.48740159, 0.6799291 , 0.46620409],
       [0.24792823, 0.90302225, 0.36170425, 0.14065124],
       [0.40962195, 0.81329592, 0.94150884, 0.629578  ]])

In [11]:
singlevel

np.float64(0.7952666435366184)

### Update

In [12]:
list_1 = np.random.rand(10)
list_2 = np.random.rand(10)

In [13]:
list_2

array([0.67564986, 0.91217228, 0.99487464, 0.77648943, 0.30994298,
       0.33717543, 0.17188459, 0.87445628, 0.56793541, 0.57277721])

In [14]:
# Basic Math
add = np.add(list_1, list_2)
sub = np.subtract(list_1, list_2)
div = np.divide(list_1, list_2)
mult = np.multiply(list_1, list_2)
dot = np.dot(list_1, list_2)

In [15]:
# Stat functions
sqrt = np.sqrt(25)
ab = np.abs(-2)
power = np.power(2,7)
log = np.log(25)
exp = np.exp([2,3])
mins = np.min(list_1)
maxs = np.max(list_1)

In [16]:
maxs

np.float64(0.9862320073607239)

In [17]:
data

array([[[0.79526664, 0.01278876, 0.04911231, 0.88678336],
        [0.45008317, 0.39721963, 0.38715577, 0.88333943],
        [0.24865133, 0.67217365, 0.81114603, 0.1140222 ]],

       [[0.42523713, 0.48740159, 0.6799291 , 0.46620409],
        [0.24792823, 0.90302225, 0.36170425, 0.14065124],
        [0.40962195, 0.81329592, 0.94150884, 0.629578  ]]])

In [18]:
data[0][0][0] = 700
data

array([[[7.00000000e+02, 1.27887562e-02, 4.91123089e-02, 8.86783357e-01],
        [4.50083166e-01, 3.97219628e-01, 3.87155775e-01, 8.83339435e-01],
        [2.48651329e-01, 6.72173647e-01, 8.11146034e-01, 1.14022195e-01]],

       [[4.25237134e-01, 4.87401590e-01, 6.79929103e-01, 4.66204086e-01],
        [2.47928235e-01, 9.03022251e-01, 3.61704255e-01, 1.40651237e-01],
        [4.09621946e-01, 8.13295923e-01, 9.41508837e-01, 6.29577998e-01]]])

In [19]:
data.sort()
data

array([[[1.27887562e-02, 4.91123089e-02, 8.86783357e-01, 7.00000000e+02],
        [3.87155775e-01, 3.97219628e-01, 4.50083166e-01, 8.83339435e-01],
        [1.14022195e-01, 2.48651329e-01, 6.72173647e-01, 8.11146034e-01]],

       [[4.25237134e-01, 4.66204086e-01, 4.87401590e-01, 6.79929103e-01],
        [1.40651237e-01, 2.47928235e-01, 3.61704255e-01, 9.03022251e-01],
        [4.09621946e-01, 6.29577998e-01, 8.13295923e-01, 9.41508837e-01]]])

In [20]:
print(data.shape)

(2, 3, 4)


In [21]:
data = data.reshape(2,2,-1)
data.shape

(2, 2, 6)

In [22]:
zeroes = np.zeros((8))
print(zeroes)
zeroes = np.append(zeroes, [3,4])
print(zeroes)

[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 3. 4.]


In [23]:
zeroes = np.insert(zeroes, 2, 1)
print(zeroes)

[0. 0. 1. 0. 0. 0. 0. 0. 0. 3. 4.]


### Delete

In [24]:
data

array([[[1.27887562e-02, 4.91123089e-02, 8.86783357e-01, 7.00000000e+02,
         3.87155775e-01, 3.97219628e-01],
        [4.50083166e-01, 8.83339435e-01, 1.14022195e-01, 2.48651329e-01,
         6.72173647e-01, 8.11146034e-01]],

       [[4.25237134e-01, 4.66204086e-01, 4.87401590e-01, 6.79929103e-01,
         1.40651237e-01, 2.47928235e-01],
        [3.61704255e-01, 9.03022251e-01, 4.09621946e-01, 6.29577998e-01,
         8.13295923e-01, 9.41508837e-01]]])

In [25]:
np.delete(data, 0, axis=1)

array([[[0.45008317, 0.88333943, 0.1140222 , 0.24865133, 0.67217365,
         0.81114603]],

       [[0.36170425, 0.90302225, 0.40962195, 0.629578  , 0.81329592,
         0.94150884]]])

In [26]:
np.save("new array", data)

In [27]:
test = np.load('new array.npy')

In [28]:
test

array([[[1.27887562e-02, 4.91123089e-02, 8.86783357e-01, 7.00000000e+02,
         3.87155775e-01, 3.97219628e-01],
        [4.50083166e-01, 8.83339435e-01, 1.14022195e-01, 2.48651329e-01,
         6.72173647e-01, 8.11146034e-01]],

       [[4.25237134e-01, 4.66204086e-01, 4.87401590e-01, 6.79929103e-01,
         1.40651237e-01, 2.47928235e-01],
        [3.61704255e-01, 9.03022251e-01, 4.09621946e-01, 6.29577998e-01,
         8.13295923e-01, 9.41508837e-01]]])