# Numpy Tutorial

In [1]:
import numpy as np

### Writing

In [4]:
data = np.random.rand(2,3,4)
zeroes = np.zeros((2,2,2))
full = np.full((2,2,2), 7)
ones = np.ones(((2,2,2)))

data, zeroes, full, ones

(array([[[0.7445119 , 0.10386351, 0.99428677, 0.03997285],
         [0.3224212 , 0.32245114, 0.5054584 , 0.3105988 ],
         [0.64258673, 0.43034009, 0.70769327, 0.2080407 ]],
 
        [[0.44395185, 0.78511044, 0.86607317, 0.74079491],
         [0.79156941, 0.07607872, 0.82690917, 0.07727112],
         [0.14305774, 0.19592186, 0.03899619, 0.16463387]]]),
 array([[[0., 0.],
         [0., 0.]],
 
        [[0., 0.],
         [0., 0.]]]),
 array([[[7, 7],
         [7, 7]],
 
        [[7, 7],
         [7, 7]]]),
 array([[[1., 1.],
         [1., 1.]],
 
        [[1., 1.],
         [1., 1.]]]))

In [6]:
arr = np.array([[1,2,3,4],[1,2,3,4]])
type(arr)

numpy.ndarray

### Reading

In [10]:
shape = data.shape
size = data.size
types = data.dtype

In [11]:
types

dtype('float64')

In [16]:
#slicing
arr = data[0]
slicer = data[0][0:2]
reverse = data[-1]
singlevel = data[0][0][0]

In [14]:
arr

array([[0.7445119 , 0.10386351, 0.99428677, 0.03997285],
       [0.3224212 , 0.32245114, 0.5054584 , 0.3105988 ],
       [0.64258673, 0.43034009, 0.70769327, 0.2080407 ]])

In [17]:
slicer

array([[0.7445119 , 0.10386351, 0.99428677, 0.03997285],
       [0.3224212 , 0.32245114, 0.5054584 , 0.3105988 ]])

In [18]:
reverse

array([[0.44395185, 0.78511044, 0.86607317, 0.74079491],
       [0.79156941, 0.07607872, 0.82690917, 0.07727112],
       [0.14305774, 0.19592186, 0.03899619, 0.16463387]])

In [19]:
singlevel

np.float64(0.74451189539489)

### Update

In [20]:
list_1 = np.random.rand(10)
list_2 = np.random.rand(10)

In [21]:
list_2

array([0.46511672, 0.43044836, 0.30175766, 0.93420312, 0.88516155,
       0.82890339, 0.57865998, 0.4640924 , 0.25584013, 0.9181496 ])

In [23]:
# Basic Math
add = np.add(list_1, list_2)
sub = np.subtract(list_1, list_2)
div = np.divide(list_1, list_2)
mult = np.multiply(list_1, list_2)
dot = np.dot(list_1, list_2)

In [24]:
# Stat functions
sqrt = np.sqrt(25)
ab = np.abs(-2)
power = np.power(2,7)
log = np.log(25)
exp = np.exp([2,3])
mins = np.min(list_1)
maxs = np.max(list_1)

In [25]:
maxs

np.float64(0.9544050938392584)

In [26]:
data

array([[[0.7445119 , 0.10386351, 0.99428677, 0.03997285],
        [0.3224212 , 0.32245114, 0.5054584 , 0.3105988 ],
        [0.64258673, 0.43034009, 0.70769327, 0.2080407 ]],

       [[0.44395185, 0.78511044, 0.86607317, 0.74079491],
        [0.79156941, 0.07607872, 0.82690917, 0.07727112],
        [0.14305774, 0.19592186, 0.03899619, 0.16463387]]])

In [27]:
data[0][0][0] = 700
data

array([[[7.00000000e+02, 1.03863511e-01, 9.94286770e-01, 3.99728549e-02],
        [3.22421203e-01, 3.22451140e-01, 5.05458402e-01, 3.10598802e-01],
        [6.42586735e-01, 4.30340090e-01, 7.07693268e-01, 2.08040703e-01]],

       [[4.43951849e-01, 7.85110440e-01, 8.66073172e-01, 7.40794911e-01],
        [7.91569408e-01, 7.60787161e-02, 8.26909173e-01, 7.72711166e-02],
        [1.43057742e-01, 1.95921856e-01, 3.89961911e-02, 1.64633872e-01]]])

In [28]:
data.sort()
data

array([[[3.99728549e-02, 1.03863511e-01, 9.94286770e-01, 7.00000000e+02],
        [3.10598802e-01, 3.22421203e-01, 3.22451140e-01, 5.05458402e-01],
        [2.08040703e-01, 4.30340090e-01, 6.42586735e-01, 7.07693268e-01]],

       [[4.43951849e-01, 7.40794911e-01, 7.85110440e-01, 8.66073172e-01],
        [7.60787161e-02, 7.72711166e-02, 7.91569408e-01, 8.26909173e-01],
        [3.89961911e-02, 1.43057742e-01, 1.64633872e-01, 1.95921856e-01]]])

In [29]:
print(data.shape)

(2, 3, 4)


In [30]:
data = data.reshape(2,2,-1)
data.shape

(2, 2, 6)

In [31]:
zeroes = np.zeros((8))
print(zeroes)
zeroes = np.append(zeroes, [3,4])
print(zeroes)

[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 3. 4.]


In [32]:
zeroes = np.insert(zeroes, 2, 1)
print(zeroes)

[0. 0. 1. 0. 0. 0. 0. 0. 0. 3. 4.]
