# Intro to Numpy

In [1]:
import numpy as np

In [3]:
#ndarray = n-dimensional array
np1 = np.array([0,1,2,3,4,5,6,7,8,9])
np1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np1.shape

(10,)

In [6]:
np2 = np.arange(10)
np2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np3 = np.arange(0,10,2)
np3

array([0, 2, 4, 6, 8])

In [8]:
np4 = np.zeros(10)
np4

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np5 = np.zeros((2,10))
np5

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [11]:
np6 = np.full((10), 6)
np6

array([6, 6, 6, 6, 6, 6, 6, 6, 6, 6])

In [12]:
np7 = np.full((2,10), 6)
np7

array([[6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6]])

In [13]:
# Converting python list to numpy
my_list = [1,2,3,4,5]
np8 = np.array(my_list)
np8

array([1, 2, 3, 4, 5])

In [14]:
np8[0]

np.int64(1)