# Searching through Numpy arrays

In [1]:
import numpy as np

In [5]:
np1 = np.array([1,2,3,4,5,6,7,8,9,10])

x = np.where(np1 == 3)
x[0]

array([2])

In [6]:
y = np.where(np1 % 2 == 0)
y[0]

array([1, 3, 5, 7, 9])

In [7]:
z = np.where(np1 % 2 == 1)
z[0]

array([0, 2, 4, 6, 8])