# Sorting Numpy Arrays

In [1]:
import numpy as np

In [2]:
np1 = np.array([6,7,4,9,1,2,10])
np.sort(np1)

array([ 1,  2,  4,  6,  7,  9, 10])

In [4]:
np2 = np.array(["John", "Tina", "Aaron"])
np.sort(np2)

array(['Aaron', 'John', 'Tina'], dtype='<U5')

In [6]:
np3 = np.array([True, False, False, True])
np.sort(np3)

array([False, False,  True,  True])

In [8]:
np4 = np.array([[6,1,3,4], [10,2,7,8]])
np.sort(np4)

array([[ 1,  3,  4,  6],
       [ 2,  7,  8, 10]])