# Filtering Numpy arrays

In [1]:
import numpy as np

In [2]:
np1 = np.array([1,2,3,4,5,6,7,8,9,10])

In [5]:
x = [True, True, False, False,False,False,False,False,False,False]
np1[x]

array([1, 2])

In [7]:
filtered = []
for thing in np1:
  if (thing % 2) == 0:
    filtered.append(True)
  else:
    filtered.append(False)
    
    
np1, filtered, np1[filtered]

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 [False, True, False, True, False, True, False, True, False, True],
 array([ 2,  4,  6,  8, 10]))