# Slicing Numpy Arrays

In [1]:
import numpy as np

In [3]:
np1 = np.array([1,2,3,4,5,6,7,8,9])
# return 2-5
print(np1[1:5])

[2 3 4 5]


In [4]:
# return 6-9
print(np1[5:])

[6 7 8 9]


In [11]:
# slicing 2D array
np2 = np.array([[1,2,3,4,5], [6,7,8,9,10]])

# slice from one row
np2[0:1, 1:3]

# slice from both rows
np2[0:2, 1:3]

array([[2, 3],
       [7, 8]])